version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Zipping deployment package"
      - zip -r app.zip index.html appspec.yml scripts/

artifacts:
  files:
    - app.zip
